### ISSUE TITLE
OSX Sierra 4D V15

### ISSUE THREAD

**Issue by algodata44** [miyako/4d-plugin-media-access-control#1]
Hi,

We use your plugin with 4D V14 and it works very well.

But we can't make it work with 4D V15...

Is there a way to build it to work with 4D V15 ?

Thanks

**Comment by miyako** [comment]
15R (64 bits) and v16 requires that the plugin uses the new v14 architecture (manifest.json). 
anyway, it's done.

**Comment by algodata44** [comment]
Thank you,

I'll try to build it.

**Comment by miyako** [comment]
you don't need to build anything. I said, it's done.

**Comment by algodata44** [comment]
Ok Thanks a lot.
